# Generated by Django 4.2 on 2025-01-25 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.faculty'),
        ),
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('OQ', "O'qituvchi"), ('KM', 'Kafedra mudiri'), ('DK', 'Dekan'), ('PR', 'Prorektor'), ('RE', 'Rektor')], max_length=2, null=True),
        ),
    ]
