# Generated by Django 4.2 on 2025-01-26 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faculty',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_faculty', to=settings.AUTH_USER_MODEL),
        ),
    ]
