# Generated by Django 5.1.5 on 2025-02-10 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_image_historicalbook_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='more_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalbook',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalbook',
            name='more_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
