# Generated by Django 4.2 on 2025-01-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_documenttype_subtitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='requirements',
            name='in_use',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
