# Generated by Django 4.2 on 2025-01-26 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_requirements_in_use_alter_document_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requirements',
            name='in_use',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
