# Generated by Django 5.1.5 on 2025-01-27 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_alter_document_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalrequirements',
            name='in_use',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='requirements',
            name='in_use',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
