# Generated by Django 5.1.5 on 2025-01-27 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_historicalrequirements_in_use_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documenttype',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='historicaldocumenttype',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
