# Generated by Django 5.1.5 on 2025-02-10 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_alter_documenttype_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='document',
            name='more_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='more_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
